alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'cloudinapicloud@gmail.com'
      smtp_auth_username: 'cloudinapicloud@gmail.com'
      smtp_auth_password: 'zyvu sqhz cymx licw'
      smtp_require_tls: true

    route:
      receiver: email-notifications
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes:
      - matchers:
        - alertname = "Watchdog"
        receiver: "null"

    receivers:
    - name: "null"

    - name: email-notifications
      email_configs:
      - to: 'cloudinapicloud@gmail.com'
        send_resolved: true
        require_tls: true
